[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "networkx==2.6.3",
    "pydot==1.4.2",
    "matplotlib==3.5.1",
    "astunparse==1.6.3",
    "numpy==1.22.1"
]
build-backend = "setuptools.build_meta"
